#!/bin/bash

cat << EOF
== $0: Disable password authentication for SSH daemon ==
EOF

CONFIG_FILE=/etc/ssh/sshd_config
REGEX="^\s*#\s*PasswordAuthentication\s\+yes\s*"
SUBSTITUTION="PasswordAuthentication no"

if grep -q $REGEX $CONFIG_FILE; then
    echo "Disabling SSH daemon password authentication"
    sudo sed -i "s/$REGEX/$SUBSTITUTION/g" $CONFIG_FILE
else
    echo "SSH daemon password authentication already disabled"
fi

cat << EOF
== $0: Finished                                      ==
EOF
