#!/bin/bash

cat << EOF
== $0: Install Wireguard ==
EOF

sudo apt update && sudo apt update -y && sudo apt install -y wireguard
#sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/g" /etc/sysctl.conf
#sudo sysctl -p

== $0: Finished          ==
EOF
